config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :questions

  root 'static_pages#mainpage'
  resources :profiles

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user

  # include votability feature
  acts_as_votable

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

  # take our picture column (string) in the db
  # treat it like PicUploader wants us to treat it
  mount_uploader :picture, PicUploader
end

app/models/question.rb
class Question < ActiveRecord::Base

	belongs_to :user

	# adding a commentability feature here
	acts_as_commentable

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  #specify that a user has one profile
  has_one :profile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :authenticate_user!

	def new
		# creating a new instance of Profile
		@profile = Profile.new
	end

	# submit butotn won't work until you do a def create
	def create
		@profile = Profile.new(profile_params)

		@profile.user = current_user

		if @profile.save
			flash[:success] = "You have created a profile"
			redirect_to profile_path(current_user.profile)
		else
			render 'new'
		end
	end

	def show
		# getting information from the URL via params
		 @profile = Profile.find(params[:id])
	end


	def profile_params
		params.require(:profile).permit(:picture, :first_name, :description)
	end


end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	
	before_action :authenticate_user!, only: :index

	def new
		@question = Question.new
		@questions = Question.all

	end

	def create 
		@question = Question.new(question_params)
		#@testing = Question.all
		@question.user = current_user

		if @question.save
			flash[:success] = "You have asked a question"
			redirect_to new_question_path
			comment = @question.comments.create
			# maybe we can eventually use this as author?
			#comment.title = "First comment."
			comment.comment = "dummy value for now"
			comment.save
		else 
			# redirect_to new_question_path
			# YOU CAN'T SAY REDIRECT HERE BECAUSE WE NEED TO KEEP TRACK OF THE @TWEET EVEN IT'S LONG SO THAT THE USER 
			# DOESN'T HAVE TO TYPE EVERYTHING ALL OVER AGAIN
			render 'new'
		end
	end

	def question_params
		params.require(:question).permit(:content)
	end

	def index
		@questions = Question.all
	end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StyleOverflow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<!-- navbar starts here -->
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <% if user_signed_in? %> 
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <% end %> 
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        
        <li>
        	<!-- right button depending on if signed in -->
        	<% if user_signed_in? %>
        		<!-- needs a method delete --> 
        		<!-- put has to do with updating -->

        		<%= link_to "Log Out", destroy_user_session_path, method: :delete %>
        	<% else %>
        		<%= link_to "Sign Up", new_user_session_path %>
        	<% end %> 
        </li>

        <li>
        	<%= link_to "Create Profile", new_profile_path %>
        </li>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>


<% flash.each do |key, value| %>
  <div class=”alert alert-<% key %>”><%=value %></div> 
<% end %>

<% if !user_signed_in? %>

<style>
  .carousel-caption {
  bottom: 50%;
  
}

img {
  max-width: 100%;
  max-height: 100%;
}


</style>
</head>

<div id="jquery-script-menu">
<div class="jquery-script-center">
<div class="jquery-script-ads"><script type="text/javascript">
</script>
<script type="text/javascript"
src="http://pagead2.googlesyndication.com/pagead/show_ads.js">
</script></div>
<div class="jquery-script-clear"></div>
</div>
</div>
<div id="myCarousel" class="carousel slide" data-ride="carousel"> 
  <!-- Indicators -->
  

  <div class="carousel-inner">
    <div class="item active"> <img src="http://wallpaperscraft.com/image/converse_ashley_clothing_style_fashion_69229_2560x1600.jpg" alt="First slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>Slide 1</h1>
          <p>Aenean a rutrum nulla. Vestibulum a arcu at nisi tristique pretium.</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Sign up today</a></p>
        </div>
      </div>
    </div>
    <div class="item"> <img src="http://oi62.tinypic.com/1zqwnqw.jpg" data-src="" alt="Second    slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>Slide 2</h1>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vitae egestas purus. </p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Learn more</a></p>
        </div>
      </div>
    </div>
    <div class="item"> <img src="http://www.freelive3dwallpapers.com/wp-content/uploads/2014/03/images-7.jpg" alt="Third slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>Slide 3</h1>
          <p>Donec sit amet mi imperdiet mauris viverra accumsan ut at libero.</p>
          <p><a class="btn btn-lg btn-primary" href="#" role="button">Browse gallery</a></p>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a> </div>
  
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-36251023-1']);
  _gaq.push(['_setDomainName', 'jqueryscript.net']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<% end %>
<!-- navbar ends here -->
<div class="container">
<%= yield %>
</div>

</body>
</html>

app/views/profiles/new.html.erb
this is a new profile page

<%= simple_form_for @profile do |f| %>
  <%= f.input :picture %>
  <%= f.input :first_name %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/profiles/show.html.erb
<div class="container">
<h1> Profile </h1>
<!--another way to do this (wrong)-->
<!--
<h3> <%= current_user.profile.first_name %> ~ <%= current_user.email %> </h3>
<h5> <%= current_user.profile.picture %> </h5>
<h5> <%= current_user.profile.description%> </h5>
-->


<h3> <%= @profile.first_name %> ~ <%= @profile.user.email%> </h3>
<ul class="list-group">
	<li class="list-group-item">
		<h5> <%= @profile.description %> </h5>
	</li>
</ul>

<!-- image profile picture -->
<%= image_tag @profile.picture %>

<!-- to style it -->
<!--
<%= image_tag @profile.picture, style: 'width:200px; heigh:200px;' %> -->
</div>

app/views/questions/new.html.erb
<%= simple_form_for @question do |f| %>
  <%= f.input :content %>
  <%= f.button :submit %>
<% end %>

<ul class="list-group">
	<% @questions.each do |question| %>
		<li class="list-group-item">
			<%= question.content %> | <%= question.user.email %>
				| 
			<% question.comments.each do |comment| %>
				<%= comment.comment %>	
			<% end %>
			
			<%= simple_form_for @question do |f| %>
			  <%= f.input :content %>
			  <%= f.button :submit %>
			<% end %>

		</li>
	<% end %>	
</ul>

app/views/static_pages/mainpage.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>